config/routes.rb
Rails.application.routes.draw do

  mount Chat::Engine => "/chat", as: "chat"
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'home#index'
  get "/about", :controller => "home", :action => "about"
  get "/load_active", :controller => "home", :action => "load_active"
  get "/load_available", :controller => "home", :action => "load_available"
  resources :games do
    patch :forfeit
  end
  resources :pieces , only: :update
  resources :users, only: :show

  post 'games/:game_id/:piece_id/:x_position/:y_position', :to => 'games#move', :as => 'move'
  get 'games/:game_id/promote/:piece_id/:x_position/:y_position', :to => 'games#promote', :as => 'promote'
  post 'games/:game_id/promoted/:old_id/:new_id/:x_position/:y_position', :to => 'games#promoted', :as => 'promoted'

  get 'games/:game_id/load_board', :controller => "games", :action => "load_board"
  get 'games/:game_id/load_display', :controller => "games", :action => "load_display"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <div class="wrapper">
    <head>
      <title>Chess</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag    'application', media: 'all' %>
      <%= javascript_include_tag 'application' %>
    </head>

    <div class="background">
      <body>
        <% unless action_name == "show" && controller_name == "games" %>
        <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <%= link_to 'Chess App', root_path, class: 'navbar-brand' %>

          
          <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-md-0">
              <li class="nav-item">
                <%= link_to 'New Game', new_game_path, class: 'nav-link' %>
              </li>
            </ul>
              <ul class="navbar-nav">
                <% if user_signed_in? %>
                  <li class="nav-item">
                    <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
                  </li>
                <% end %>
              </ul>
          </div>
        </nav>
        <% end %>
        <%= yield %>

      </body>
    </div>
    <% unless action_name == "show" && controller_name == "games" %>
    <footer>
      <div id="footer">
        <div>
          <ul class="float-left">
          
              <li class="nav-item">
                <%= link_to 'About', about_path, class: 'nav-link' %>
              </li>
          
          </ul>
        </div>
      </div>
    </footer>
    <% end %>
  </div>
</html>